### ISSUE TITLE
Recipe for Stellar Alloy doesn't work in Advanced Carpenter

### ISSUE THREAD

**Issue by Aixler** [ThePansmith/Enigmatica2ExpertUnofficialSkyblock#13]
Modpack version
Enigmatica 2 Expert Skyblock Unoffical - 1.3.7.3

Issue
Recipe for Stellar Alloy doesn't work. I'm certain I've input the correct items and fluid.

I've attached a picture of the recipe. As you can see the top left icon is missing. Maybe this is related?
![image](https://github.com/ThePansmith/Enigmatica2ExpertUnofficialSkyblock/assets/8914693/7d924262-9a09-40ca-8ef8-1fe0b32030cb)

**Comment by Aixler** [comment]
Tested in 1.3.8.1 - exact same issue

**Comment by ThePansmith** [comment]
fixed in 1.3.8.2
