### ISSUE TITLE
[1.1.0] Issue in Armor.zs

### ISSUE THREAD

**Issue by wesolowskidawid** [ThePansmith/Enigmatica2ExpertUnofficialSkyblock#3]
Pack version: 1.1.0

After removing twilight forest, there is an issue in recipe in Armor.zs line 246: 

`mods.extendedcrafting.CombinationCrafting.addRecipe(<draconicevolution:wyvern_helm>, 1000000000, 1000000, <draconicevolution:wyvern_energy_core>, **[,** <minecraft:chainmail_helmet>.anyDamage(),<nuclearcraft:helm_boron_nitride>.anyDamage(),<botania:terrasteelhelm>.anyDamage(),<mysticalagriculture:supremium_helmet>.anyDamage(),<tcomplement:manyullyn_helmet>.anyDamage(),<draconicevolution:wyvern_core>,<ic2:quantum_helmet>.anyDamage(),<draconicevolution:draconium_block:1>,<draconicevolution:draconium_block:1>,<draconicevolution:draconium_block:1>,<draconicevolution:draconium_block:1>]);`

ERROR: Error parsing Armor.zs:246 -- Invalid expression, last token: ,

In the branch updated last week there is a helmet from twilight forest, I guess you missed it there. 
Really enjoying the pack good job man :)

**Comment by ThePansmith** [comment]
Thanks for submitting, fixed in 1.1.1
