### ISSUE TITLE
Thaumcraft "Hedge Alchemy 3/4" uncompletable

### ISSUE THREAD

**Issue by Laser-Cakes** [ThePansmith/Enigmatica2ExpertUnofficialSkyblock#5]
**Modpack version**
1.2.0.0

**Issue**
Unable to complete "Hedge Alchemy 3/4" as the Wheat - String recipe in the Thaumcraft Crucible does not work.  Additionally the String - Cobweb recipe is missing (does not have any aspects) and also doesn't function.

**Logs**
Wheat - String
https://www.youtube.com/watch?v=sr0P1x2gHSA

String - Cobweb
https://i.imgur.com/hrpl0hZ.png

**Comment by ThePansmith** [comment]
"Fixed" in 1.2.1.0 by removing TC speedup. I'll have to see about getting rong to update the mod.
