### ISSUE TITLE
Twilight Forest Ingots in Creative.zs - scripts

### ISSUE THREAD

**Issue by accessdenied0** [ThePansmith/Enigmatica2ExpertUnofficialSkyblock#7]
**Modpack version**
1.3.6

**Issue**
Twilight Forest or not?

**Logs**
-

*Description*
I noticed that the first time installed that back... way back, it still had Twilight Forest, but I avoided it and it got soon removed.
All new Instances I installed (1.2.5.0+), didn't have it in it, as expected.
But since the 1.3.5 version it showed up again in the Creative Scripts, I copied some old Scripts over, since I don't expect it to be actually in the pack, but I need to clarify this, since I am not sure where this pack might direct.

I thank you for your work!

**Comment by ThePansmith** [comment]
fixed in 1.3.6

**Comment by accessdenied0** [comment]
I used 1.3.6 in my report and still had this issues and the ingots in the script.

I just first noticed it at 1.3.5.

For safety I checked and updated a new Version but the issue preist.

_Edit:_ in addition, the twilight-forest and some Biomes o' Plenty rewards aren't removed either.

**Comment by ThePansmith** [comment]
Whoops, missed an ingot, thanks for catching that.

As for defaultloot, its per world, bq_admin reload doesn't reload it for some reason, so delete it and let the game regenerate it.
